import type { AchievementDefinition, AchievementGroup, AchievementPostGameOrigin } from './achievement-types'

const NORMAL: AchievementPostGameOrigin = 'normal'
const CHALLENGE: AchievementPostGameOrigin = 'challenge'
const SHOP: AchievementPostGameOrigin = 'shop'

export const ACHIEVEMENT_GROUPS: AchievementGroup[] = [
  { category: 'level', label: 'Nível' },
  { category: 'single-score', label: 'Score em partida' },
  { category: 'lifetime-score', label: 'Score acumulado' },
  { category: 'challenges', label: 'Desafios' },
  { category: 'game-changer', label: 'Game changers' },
  { category: 'auto-check', label: 'Auto-check' },
  { category: 'curiosity', label: 'Curiosidade' },
  { category: 'shop', label: 'Loja' },
  { category: 'profile', label: 'Perfil' },
  { category: 'daily', label: 'Meta diária' },
  { category: 'tutorial', label: 'Tutorial' },
]

export const ACHIEVEMENT_CATALOG: AchievementDefinition[] = [
  {
    id: 'level-10',
    category: 'level',
    postGameOrigin: NORMAL,
    title: 'Nv. 10',
    description: 'Alcance o nível 10 do jogador.',
    metric: { kind: 'level', targetLevel: 10 },
  },
  {
    id: 'level-20',
    category: 'level',
    postGameOrigin: NORMAL,
    title: 'Nv. 20',
    description: 'Alcance o nível 20 do jogador.',
    metric: { kind: 'level', targetLevel: 20 },
  },
  {
    id: 'level-30',
    category: 'level',
    postGameOrigin: NORMAL,
    title: 'Nv. 30',
    description: 'Alcance o nível 30 do jogador.',
    metric: { kind: 'level', targetLevel: 30 },
  },
  {
    id: 'level-40',
    category: 'level',
    postGameOrigin: NORMAL,
    title: 'Nv. 40',
    description: 'Alcance o nível 40 do jogador.',
    metric: { kind: 'level', targetLevel: 40 },
  },
  {
    id: 'level-50',
    category: 'level',
    postGameOrigin: NORMAL,
    title: 'Nv. 50',
    description: 'Alcance o nível 50 do jogador.',
    metric: { kind: 'level', targetLevel: 50 },
  },
  {
    id: 'level-100',
    category: 'level',
    postGameOrigin: NORMAL,
    title: 'Nv. 100',
    description: 'Alcance o nível 100 do jogador.',
    metric: { kind: 'level', targetLevel: 100 },
  },
  {
    id: 'single-score-200',
    category: 'single-score',
    postGameOrigin: NORMAL,
    title: '200 pontos',
    description: 'Consiga 200 pontos em uma única partida normal.',
    metric: { kind: 'best-score-normal', target: 200 },
  },
  {
    id: 'single-score-500',
    category: 'single-score',
    postGameOrigin: NORMAL,
    title: '500 pontos',
    description: 'Consiga 500 pontos em uma única partida normal.',
    metric: { kind: 'best-score-normal', target: 500 },
  },
  {
    id: 'single-score-1000',
    category: 'single-score',
    postGameOrigin: NORMAL,
    title: '1000 pontos',
    description: 'Consiga 1000 pontos em uma única partida normal.',
    metric: { kind: 'best-score-normal', target: 1000 },
  },
  {
    id: 'lifetime-score-100k',
    category: 'lifetime-score',
    postGameOrigin: NORMAL,
    title: '100 mil',
    description: 'Acumule 100.000 pontos de score em partidas normais.',
    metric: { kind: 'lifetime-score-normal', target: 100_000 },
  },
  {
    id: 'lifetime-score-500k',
    category: 'lifetime-score',
    postGameOrigin: NORMAL,
    title: 'Meio milhão',
    description: 'Acumule 500.000 pontos de score em partidas normais.',
    metric: { kind: 'lifetime-score-normal', target: 500_000 },
  },
  {
    id: 'lifetime-score-1m',
    category: 'lifetime-score',
    postGameOrigin: NORMAL,
    title: 'Milionário',
    description: 'Acumule 1.000.000 pontos de score em partidas normais.',
    metric: { kind: 'lifetime-score-normal', target: 1_000_000 },
  },
  {
    id: 'challenges-30',
    category: 'challenges',
    postGameOrigin: CHALLENGE,
    title: 'Desafiante',
    description: 'Conclua 30 desafios.',
    metric: { kind: 'challenges-completed', target: 30 },
  },
  {
    id: 'gc-plus-99',
    category: 'game-changer',
    postGameOrigin: NORMAL,
    title: '+99',
    description: 'Complete 10 modificadores +99 em partidas normais.',
    metric: { kind: 'game-changer', key: 'plus99', target: 10 },
  },
  {
    id: 'gc-minus-1',
    category: 'game-changer',
    postGameOrigin: NORMAL,
    title: '-1',
    description: 'Complete 10 modificadores -1 em partidas normais.',
    metric: { kind: 'game-changer', key: 'minus1', target: 10 },
  },
  {
    id: 'gc-times-div',
    category: 'game-changer',
    postGameOrigin: NORMAL,
    title: '×÷',
    description: 'Complete 10 modificadores ×÷ em partidas normais.',
    metric: { kind: 'game-changer', key: 'timesDiv', target: 10 },
  },
  {
    id: 'gc-four-seconds',
    category: 'game-changer',
    postGameOrigin: NORMAL,
    title: '4s',
    description: 'Complete 10 modificadores 4s em partidas normais.',
    metric: { kind: 'game-changer', key: 'fourSeconds', target: 10 },
  },
  {
    id: 'auto-check-earned',
    category: 'auto-check',
    postGameOrigin: NORMAL,
    title: 'Auto Check',
    description: 'Ganhe um auto check durante uma partida normal.',
    metric: { kind: 'auto-checks-earned-normal' },
  },
  {
    id: 'zero-score-game-over',
    category: 'curiosity',
    postGameOrigin: NORMAL,
    title: 'Zero absoluto',
    description: 'Perca um jogo normal sem acertar nenhum cálculo.',
    metric: { kind: 'zero-score-game-over' },
  },
  {
    id: 'shop-one-per-category',
    category: 'shop',
    postGameOrigin: SHOP,
    title: 'Comprador',
    description: 'Compre um item pago de tema, tag, efeito e teclado.',
    metric: { kind: 'shop-one-per-category' },
  },
  {
    id: 'shop-all-paid-items',
    category: 'shop',
    postGameOrigin: SHOP,
    title: 'Colecionador',
    description: 'Compre todos os itens pagos da loja.',
    metric: { kind: 'shop-all-paid-items' },
  },
  {
    id: 'avatar-photo-saved',
    category: 'profile',
    postGameOrigin: SHOP,
    title: 'Selfie',
    description: 'Salve ou troque a foto de avatar.',
    metric: { kind: 'avatar-photo-saved' },
  },
  {
    id: 'daily-goal-once',
    category: 'daily',
    postGameOrigin: NORMAL,
    title: 'Ponto batido',
    description: 'Complete a meta diária de pontos pela primeira vez.',
    metric: { kind: 'daily-goals-completed', target: 1 },
  },
  {
    id: 'daily-goal-10',
    category: 'daily',
    postGameOrigin: NORMAL,
    title: 'Trabalhador',
    description: 'Complete a meta diária de pontos 10 vezes.',
    metric: { kind: 'daily-goals-completed', target: 10 },
  },
  {
    id: 'plus-one-genius',
    category: 'curiosity',
    postGameOrigin: NORMAL,
    title: 'Gênio da matemática',
    description: 'Acerte um cálculo qualquer número + 1.',
    metric: { kind: 'plus-one-calculation-solved' },
  },
  {
    id: 'tutorial-completed',
    category: 'tutorial',
    postGameOrigin: SHOP,
    title: 'Aprendiz',
    description: 'Conclua o tutorial do jogo.',
    metric: { kind: 'tutorial-completed' },
  },
]

export const ACHIEVEMENT_TOTAL_COUNT = ACHIEVEMENT_CATALOG.length
